const CITY_NAME_MAP: Record<string, string> = {
  // Ukrainian cities
  'київ': 'Kyiv',
  'львів': 'Lviv',
  'одеса': 'Odesa',
  'харків': 'Kharkiv',
  'дніпро': 'Dnipro',
  'запоріжжя': 'Zaporizhzhia',
  'вінниця': 'Vinnytsia',
  'миколаїв': 'Mykolaiv',
  'херсон': 'Kherson',
  'полтава': 'Poltava',
  'чернігів': 'Chernihiv',
  'черкаси': 'Cherkasy',
  'суми': 'Sumy',
  'житомир': 'Zhytomyr',
  'рівне': 'Rivne',
  'івано-франківськ': 'Ivano-Frankivsk',
  'тернопіль': 'Ternopil',
  'хмельницький': 'Khmelnytskyi',
  'луцьк': 'Lutsk',
  'ужгород': 'Uzhhorod',
  'чернівці': 'Chernivtsi',
  'кропивницький': 'Kropyvnytskyi',
  'маріуполь': 'Mariupol',
  'краматорськ': 'Kramatorsk',
  // European capitals and major cities
  'лондон': 'London',
  'париж': 'Paris',
  'берлін': 'Berlin',
  'рим': 'Rome',
  'мадрид': 'Madrid',
  'варшава': 'Warsaw',
  'прага': 'Prague',
  'відень': 'Vienna',
  'амстердам': 'Amsterdam',
  'брюссель': 'Brussels',
  'стокгольм': 'Stockholm',
  'осло': 'Oslo',
  'копенгаген': 'Copenhagen',
  'гельсінкі': 'Helsinki',
  'афіни': 'Athens',
  'будапешт': 'Budapest',
  'бухарест': 'Bucharest',
  'белград': 'Belgrade',
  'загреб': 'Zagreb',
  'братислава': 'Bratislava',
  'любляна': 'Ljubljana',
  'таллінн': 'Tallinn',
  'рига': 'Riga',
  'вільнюс': 'Vilnius',
  'мінськ': 'Minsk',
  'кишинів': 'Chisinau',
  'тбілісі': 'Tbilisi',
  'єреван': 'Yerevan',
  'баку': 'Baku',
  'анкара': 'Ankara',
  'стамбул': 'Istanbul',
  // World cities
  'москва': 'Moscow',
  'нью-йорк': 'New York',
  'лос-анджелес': 'Los Angeles',
  'чикаго': 'Chicago',
  'токіо': 'Tokyo',
  'пекін': 'Beijing',
  'шанхай': 'Shanghai',
  'дубай': 'Dubai',
}

export const normalizeCityName = (cityName: string): string => {
  const trimmed = cityName.trim()
  return CITY_NAME_MAP[trimmed.toLowerCase()] ?? trimmed
}
